### ISSUE TITLE
Replace yaml_model

### ISSUE THREAD

**Issue by RickyCook** [RickyCook/DockCI#177]
As sad as it is, YAML model is too simplistic for DockCI, and other projects that will need to be integrated.

**Questions:**
- RDBMS or NoSQL? Tending towards RDBMS

**Comment by ps-jay** [comment]
Oh no!

**Comment by RickyCook** [comment]
Yeah :( It's a bummer. I really like YAML model, but its indexing (which I managed to add :D) is way too simplistic, it has no transactions, and I'm not sure it will scale. It needs to happen... Just not sure when! ><
