### ISSUE TITLE
require.js fails to load after booting dockci in docker according to the README.

### ISSUE THREAD

**Issue by adammacleod** [RickyCook/DockCI#296]
I followed the README instructions to get dockci running via docker-compose and the when loading the main page I get an error including require.js:

![image](https://cloud.githubusercontent.com/assets/397073/10685676/82e6f970-79a8-11e5-9aa9-435c1e0b9016.png)

**Comment by RickyCook** [comment]
Would you be able to send me the build log? On slack or something is fine

**Comment by RickyCook** [comment]
Oh wait no I know why that is :p

**Comment by RickyCook** [comment]
Quick fix if you just want to get dockci running is remove the /code/dockci volume mount in the compose file
