### ISSUE TITLE
JWT endpoints not returning as expected.

### ISSUE THREAD

**Issue by adammacleod** [RickyCook/DockCI#320]
I can successfully POST Basic Auth to /api/v1/me:

	POST /api/api/v1/me HTTP/1.1
	Host: localhost:3000
	Connection: keep-alive
	Content-Length: 51
	accept: application/json
	Origin: http://localhost:3000
	User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
	authorization: Basic <redacted>
	content-type: application/json
	Referer: http://localhost:3000/
	Accept-Encoding: gzip, deflate
	Accept-Language: en-US,en;q=0.8

	{
	    "active": true,
	    "confirmed_at": null,
	    "email": "adam@macleod.id.au",
	    "id": 1
	}

However, the same POST to /api/v1/me/jwt fails:

	POST /api/api/v1/me/jwt HTTP/1.1
	Host: localhost:3000
	Connection: keep-alive
	Content-Length: 51
	accept: application/json
	Origin: http://localhost:3000
	User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
	authorization: Basic <redacted>
	content-type: application/json
	Referer: http://localhost:3000/
	Accept-Encoding: gzip, deflate
	Accept-Language: en-US,en;q=0.8

	{
	    "message": {
	        "name": "(Service name for the token)  Missing required parameter in the JSON body or the post body or the query string"
	    }
	}

I would expect that /api/v1/me/jwt returns a JWT token.

**Comment by RickyCook** [comment]
That's expected. 

You need to give a name to the token. The plan was to allow for future revokation of tokens, so I added the service name field now so that it's easy to see what purpose the token serves.

**Comment by adammacleod** [comment]
Ah. Fair enough. In respect to logging in the user on the front end should I just give the token a common name like 'spruce-ui' or something?

**Comment by RickyCook** [comment]
yup. we can ignore those in any other part of the UI

**Comment by adammacleod** [comment]
Oh nice, works perfectly :)

**Comment by RickyCook** [comment]
awesome! I really like this auth model, because it means you can use token, u/p, or cookie (and token, u/p can be used as get/post params, headers, etc anywhere too)
