### ISSUE TITLE
Debian as host OS rather than Ubuntu

### ISSUE THREAD

**Issue by sammcj** [RickyCook/DockCI#42]
As discussed - it would be advisable to use Debian as the host OS rather than Ubuntu

**Comment by RickyCook** [comment]
I was very surprised that you closed that.....

**Comment by sammcj** [comment]
I was staring at it hoping that it would resolve itself, then I saw it hadn't and Ubuntu gave me the shivers which triggered a chain reaction where my hand hit the close button.

**Comment by RickyCook** [comment]
Like they do with legitimate issues of stability? Must have been what happened with USB keyboard drivers

**Comment by sammcj** [comment]
How dare you!, Ubuntu has a flawless reputation of quality packaging, they'd certainly never break critical features of the operating system during upgrades, ever... right? :hankey:

**Comment by RickyCook** [comment]
Psh nobody was using USB anyway

**Comment by ps-jay** [comment]
I really want CentOS 5 being the target.  2.6.18 is awesome.

**Comment by RickyCook** [comment]
Great idea! 2.6 +480 patches make it total Docker safe

**Comment by sammcj** [comment]
I hear CentOS is all the rage with 'enterprise' these days... :postbox:

**Comment by RickyCook** [comment]
Is that an money box with silver cents being put into it or are you just happy to see stable kernels?
